param = {
    "add_ef2dir": True,
    "batch_size": 64,
    "cutoff": 7,
    "dir2mask_tailact": False,
    "ef2mask_tailact": True,
    "ef_decay": True,
    "ef_dim": 96,
    "ev_decay": True,
    "hid_dim": 256,
    "ln_emb": False,
    "lr": 0.0003,
    "num_mplayer": 8,
    "patience": 20,
    "rbf": "nexpnorm",
    "rbound_lower": 0.0,
    "warmup": 20,
    'ln_lin1': True,
    'ln_s2v': True,
    'max_z': 20,
    'wd': 0,
    'lin1_tailact': True,
    "use_dir1": False
}